#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'career_center'
require 'pry'

Pry.cli = true
Pry.start(Pry.toplevel_binding)
